### ISSUE TITLE
Turn The Dice Into an Object

### ISSUE THREAD

**Issue by 80cmdude** [Thatdwarf/DiceRoller#1]
Create a Dice Object with 2 properties. Dice number and dice sides.

To Do this, Create a new class and define how to  create the object then in the main class create a new object and parse in the values into your roll function.

**Comment by 80cmdude** [comment]
So at the moment you have created an object with no properties. Then you are just running functions that are inside that class. You are correct to create a new instance of the object in main (gets over the static problem). You need to define the Object properties in the other class. To do this have a look up about {get; set;}. Then you can do (in main) int dicesides = newdiceobject.sides instead of having to run the function. This is because when you create the object (Diceobject newdiceobject = new Diceobject(); ) then it will automaticall realise that it has 3 properties....

Let me know if ive confused you

**Comment by 80cmdude** [comment]
Defo Getting there though your picking it up fast

**Comment by Thatdwarf** [comment]
Think i've done that now

**Comment by 80cmdude** [comment]
Ill have a look today :)

**Comment by 80cmdude** [comment]
I was having trouble Pushing to this coz permissions so here is the file / comments i have added to help you

http://ge.tt/3PdnSKc2

Let me know what else you need

**Comment by 80cmdude** [comment]
// NEW CLASS CALLED DICE AND THE USE CODE BELOW. THIS TELLS THE PROGRAM HOW TO CREATE A DICE OBJECT.

public class Dice {
    private int DiceAmount = 0
    private int DiceSides = 0
    private int DiceMod = 0

```
//constructor
public Dice(int diceAmount, int diceSides, int diceMod) {
    DiceAmount = diceAmount;
    DiceSides = diecSides;
    DiceMod = diceMod;
}
```

}

// IN THE DICESETUP CLASS
DiceSetup() {
        System.out.println("Enter the amount of dice to roll.");
        diceAmount  = user_input.nextInt();                  // Waits for input. strings end app
        System.out.println("Enter the amount of side the dice have.");
        diceSides = user_input.nextInt();                   // Waits for input. strings end app
        System.out.println("Enter roll Modifier (+/-).");
        diceMod = user_input.nextInt();                     // Waits for input. strings end app

```
    //Create your fancy new object here and pass in your newly created shit.
    Dice D = new Dice(diceAmount, diceSides, diceMod)
    // Here is your new obect (D) That you can manipuate and shit
}
// CONGRATES ON OUR FANCY NEW OBJECT. You can access the object info by doing D.diceAmount, D.diceMod etc OR GET REALLY FANCY AND.....
```

// I couldnt see if you had a fucntion to roll or not but what you can do now is create a roll() {}; function and pass in the object!!! roll(object d1) {}; then it should automatically pick up all the properties of that dice so you can be like : Roll(object d1) {d1.diceAmount, d1.diceMod} Etc!! 
All you do to is call the roll function and pass in D in your main program . (roll(D););

**Comment by 80cmdude** [comment]
That formatted it really weird but you get the idea

**Comment by Thatdwarf** [comment]
ok think ive done it this time but few notes
1. code above didnt work might have entered wrong but the dice object was not findable in main (left in Dice-Object branch for you to check) 
2. think i already have the object you were after in just poorly named (cleaned up in Roll-Method branch).

ps Roll-Method is the more updated one with Dice-Object just there to check how i messed up

**Comment by 80cmdude** [comment]
I pushed a new Branch. its a very quick fix i cant test it coz no compiler

Let me know if thats confusing ill look again tomorrow

**Comment by Thatdwarf** [comment]
yeah same issue as i had Dice object not found in main

**Comment by 80cmdude** [comment]
okay ill have a look tommorow when i have a bit more time. But have a play around with that for now.

**Comment by Thatdwarf** [comment]
think i prefer how it is in the Roll-Method branch with the constructor of dice have the input codes so any new dice object is setup on creation

**Comment by 80cmdude** [comment]
Thats perfect Dom. I realised on my way home why it was not working. I had a look at my own code. I have done the same as in your Roll-Method Branch. That is perfect. Sorry for the confusion i was writing in a text editor with no color or intellisense......in a language i dont know....quickly coz i wanted to go home..... i was close enough. :p.. Go ahead and merge that in!

**Comment by Thatdwarf** [comment]
cheers and no worries i know your input wont be perfect for the reasons you said 
also what was wrong with the other code?

**Comment by 80cmdude** [comment]
Which other code?

**Comment by Thatdwarf** [comment]
removed it now so nvm
