### ISSUE TITLE
Now you can roll the dice.....

### ISSUE THREAD

**Issue by 80cmdude** [Thatdwarf/DiceRoller#3]
Here is the final test.

So you can roll a dice.. which means you have an RNG calculator....

Time to make a simple game....

Deathwing has 400hp. Your weapon has between 10-30 dmg. You have 200hp and deathwing can attack for 40-50 dmg. You can block his attack if you roll higher on his turn. 

RNGESUS FOR THE WIN. GOGOGO

**Comment by 80cmdude** [comment]
Might have to play around with the numbers to get it to be balanced.

Clearer Rules
1. You have 200hp
2. Deathwing has 400hp
3. Your wep does between 10-30dmg
4 He does 30-40 dmg
5. You can block his dmg if you roll higher on his turn then parry for 30-40 dmg

**Comment by Thatdwarf** [comment]
Done a basic fight system atm (right now is just a slug fest with flat damage) will add more later also i now see what you meant with the using the values of an object not as i am atm taking out a copy and using those.

**Comment by 80cmdude** [comment]
Nice man seems like you are starting to nail objects... You are even using the this keyword. Fuck this. this is stupid and i hate it. You will understand why soon

**Comment by Thatdwarf** [comment]
ok now i think i have properly done the act on an object (in battler branch in player/boss turn methods) 

apologies in advance all in 1 code now (turns out java can only extend to one other so i need to clean it up a bit later)

**Comment by 80cmdude** [comment]
Had a quick glance over it! So the Dice object is perfect now i hope that you have a better understanding that you get. I do just have 1 request for best practice, its starting to get to the stage where it is looking quite different to C#. Would it be possible to comment the shit out of it so i can find stuff at a quick glance? I know its annoying as hell but its really good practice to get into the habbit of commenting pretty much every line. If you do that you become a very popular dev very quickly.

I think you could probably go a step further and make the boss a non static object ;). To do this you would HAVE to use the "this" keyword(you already are). But this will help you to understand a bit more about why and when it is good to use.(at the moment you do not HAVE to use the this keyword in your code. It is optional).

Apart from that looking good. I found a way to get Java into Visual studio (by accident when i was installing something else - iOS related) so i may have a look at this at some point.

**Comment by Thatdwarf** [comment]
Will do (not today as grad but will do)

**Comment by 80cmdude** [comment]
Good Luck!

**Comment by Thatdwarf** [comment]
Notations updated

**Comment by 80cmdude** [comment]
Dude this is really good. I'm impressed you've picked this up so quickly. Only 1 thing is still needs more comments. The general convention is that you comment pretty much every line (unless there is a really REALLY good reason not to - ie. I think most people know what "if" means). Comments always go above the line of code. Yes its annoying and it looks stupid. But after a while you get used to it and get into the habit and actually it looks quite good, especially if your compiler makes the comments a darker color. Dont take my github stuff as an example for comments. I was terrible back then but everything i do at work has a comment. 

Other than that this is really good..... You've kinda made me wanna go back and beat it. Like right now without significant research i don't think i could code what you've done in C# very quickly!

**Comment by 80cmdude** [comment]
However with the comments you have added and a little bit more time i understand it alot better. I think we can go ahead and close this issue then i can give the next task? ;)

**Comment by Thatdwarf** [comment]
Can do prob wont get on to it for a little bit (far too hot and the interview for the job that wanted java is tomorrow)

**Comment by 80cmdude** [comment]
Ah nice well good luck for that. Hopefully it all goes well. Looks like you have the basics!
